config/routes.rb
Naeti::Application.routes.draw do

  resources :waitinglists

  resources :coursedates

  resources :credit_card_types

  resources :expiration_years

  resources :expiration_months

  resources :states

  devise_for :users
  
  
  resources :content_blocks

  resources :order_items

  resources :shopping_cart_items

  resources :user_roles

  resources :orders

  resources :shopping_carts

  resources :course_registrants

  resources :course_assets

  resources :course_categories

  resources :course_dates

  resources :on_site_trainings

  resources :checkouts
  

  match '/admin', :to=>"admin#index"
  match '/reports', :to=>"admin#reports"
  
  match '/instructors', :to=>"instructors#index"
  match '/instructors/course/:course_id', :to=>"courses#admin_instructor_edit"
  match '/admin/course/:course_id', :to=>"courses#admin_instructor_edit"
  
  match '/instructors/courses', :to=>"courses#instructor_list"
  match '/instructors/search_courses', :to=>"instructors#instructor_search"
  
  match '/on-site-training', :to=>"site#on_site_training"

  resources :courses do
    collection do
      post :search
    end
  end
  
 match '/courses/register/:friendly_course_url', :to=>"courses#register"
  
 match '/courses/:course_id/export_emails', :to=>"courses#export_emails"
 match '/courses/:course_id/export_xls', :to=>"courses#export_xls"
 match '/courses/:course_id/export_pdf', :to=>"courses#export_pdf", :defaults => { :format => 'pdf' }
 match '/courses/:course_id/coursereport-:course_id-:datestamp', :to=>"courses#export_pdf", :defaults=>{:format=>"pdf"}
  

  match '/users/:user_id/add_to_course', :to=>"users#add_to_course"
  
  resources :users do
    collection do
      post :search
      post :upload
      post :user_admin
    end
  end

  match '/:friendly_url', :to=>"site#static_page"
  

  namespace :admin do
    resources :registrants
    resources :assets
    resources :user_assets
    resources :course_assets
    resources :order_items do
      collection do
        post :search
        get :confirm
      end
    end  
    resources :courses do
      collection do
        post :search
        post :upload
        post :send_reminder
      end
    end  
  end
  
  

  root :to => "site#index"

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to  :order
  belongs_to  :course
  belongs_to  :course_date
  belongs_to  :registrant
  
  default_scope order("created_at desc")
  
  scope :confirmed, where(:is_confirmed=>true)
  
end

app/controllers/admin/order_items_controller.rb
class Admin::OrderItemsController < ApplicationController
  before_filter :authenticate_admin
    
  # GET /order_items
  # GET /order_items.xml
  def index
    @page_title = "Transactions"
    @admin_section = true

    @order_items = OrderItem.page(params[:page]).per(10) 

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @order_items }
    end
  end

  # GET /order_items/1
  # GET /order_items/1.xml
  def show
    @order_item = OrderItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order_item }
    end
  end

  # GET /order_items/new
  # GET /order_items/new.xml
  def new
    @order_item = OrderItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order_item }
    end
  end

  # GET /order_items/1/edit
  def edit
    @order_item = OrderItem.find(params[:id])
  end

  # POST /order_items
  # POST /order_items.xml
  def create
    @order_item = OrderItem.new(params[:order_item])

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to(@order_item, :notice => 'Order item was successfully created.') }
        format.xml  { render :xml => @order_item, :status => :created, :location => @order_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /order_items/1
  # PUT /order_items/1.xml
  def update
    @order_item = OrderItem.find(params[:id])

    respond_to do |format|
      if @order_item.update_attributes(params[:order_item])
        format.html { redirect_to(@order_item, :notice => 'Order item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.xml
  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy

    respond_to do |format|
      format.html { redirect_to(order_items_url) }
      format.xml  { head :ok }
    end
  end

  def search
    @page_title = "Transactions"
    @admin_section = true

    @order_items=OrderItem.joins(:registrant).select("distinct order_items.*").where('registrants.email LIKE ? OR registrants.first_name LIKE ? OR registrants.last_name LIKE ? OR order_items.po_number LIKE ?', "%#{[params[:search_term]]}%", "%#{[params[:search_term]]}%", "%#{params[:search_term]}%", "%#{[params[:search_term]]}%")
    
    @order_items = @order_items.where('order_items.created_at >= ? AND order_items.created_at <= ?', "#{params[:from]} 00:00:00", "#{params[:to]} 23:59:59") if (params[:to].present? && params[:from].present?)
   
    #@order_items = @order_items.page(params[:page]).per(10)
    render :action=>"index"  
    
  end

  def confirm
    @order_item = OrderItem.find(params[:id])
    @order_item.is_confirmed=true

    respond_to do |format|
      if @order_item.save
        format.js {}
      end
    end
        
  end
    
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_filter :authenticate_admin
  
  # GET /order_items
  # GET /order_items.xml
  def index
    @order_items = OrderItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @order_items }
    end
  end

  # GET /order_items/1
  # GET /order_items/1.xml
  def show
    @order_item = OrderItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order_item }
    end
  end

  # GET /order_items/new
  # GET /order_items/new.xml
  def new
    @order_item = OrderItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order_item }
    end
  end

  # GET /order_items/1/edit
  def edit
    @order_item = OrderItem.find(params[:id])
  end

  # POST /order_items
  # POST /order_items.xml
  def create
    @order_item = OrderItem.new(params[:order_item])

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to(@order_item, :notice => 'Order item was successfully created.') }
        format.xml  { render :xml => @order_item, :status => :created, :location => @order_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /order_items/1
  # PUT /order_items/1.xml
  def update
    @order_item = OrderItem.find(params[:id])

    respond_to do |format|
      if @order_item.update_attributes(params[:order_item])
        format.html { redirect_to(@order_item, :notice => 'Order item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.xml
  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy

    respond_to do |format|
      format.html { redirect_to(order_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/admin/order_items/_confirmation.html.erb
<strong>
  <% if order_item.is_confirmed? %>
    Yes
  <% else %>
    No
    <br><br>
    <%= link_to "Confirm Now!", confirm_admin_order_items_path(:id=>order_item.id), :remote=>true %>
  <% end %>
</strong>

app/views/admin/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :course_date_id %><br />
    <%= f.text_field :course_date_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/order_items/confirm.js.erb
$(".confirmation_<%=@order_item.id%>").html("<%= escape_javascript(render :partial=>"confirmation", :locals=>{:order_item=>@order_item}) %>");

app/views/admin/order_items/edit.html.erb
<h1>Editing order_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/admin/order_items/index.html.erb
		<div id="small_table">
		<div class="footer"></div>
			<h2>Search</h2>
			
			<table id="search_class" style="width:100%" border="0" cellspacing="15px" cellpadding="15">
			<%form_tag "/admin/order_items/search", :method=>"post" do%>
				<tr><th>Keywords (registrant first name,registrant last name,registrant email, po number):<br><br></th> </tr>
				<tr>
					<td colspan="2"><input class="text" type="text" name="search_term" value="<%=params[:search_term]%>" id="some_name">
					&nbsp;&nbsp;-or-&nbsp;&nbsp;<%= link_to "reset", admin_order_items_path %></td>
					
				</tr>
				<tr>
				<tr><th>Order Date Range:<br><br></th> </tr>

				<td>
				
				<div class="datefinder">

                  <label for="from">From</label>
                  <input type="text" id="from" name="from" value="<%=params[:from]%>"/>
                  <label for="to">To</label>
                  <input type="text" id="to" name="to" value="<%=params[:to]%>"/>
                </div>

				</td>
				</tr>

				<tr>
					<td style="padding: 0 80px"><input type="submit" name="some_name" value="" id="some_name" class="search_btn"></td>
				</tr>
				<%end%>
			</table>
			
		</div>
		<div id="large_table">
		<div id="header_bg">
		<table colspan="5" class="zebra">
			<tr class="header">
				<th>Registrant</th>
				<th>Course</th>
				<th>Order Info</th>
				<th>Confirmation</th>

			</tr>
			<% @order_items.each do |order_item|%>
			<tr style="vertical-align:top">
 			    <td style="padding:20px 3px">
 			      <strong>
 			      <%= order_item.registrant.first_name %>
 			      <%= order_item.registrant.last_name %><br>
 			      <%= order_item.registrant.company_name if order_item.registrant.company_name.present? %><br>
 			      </strong>
 			      <%= order_item.registrant.address %><br>
 			      <%= order_item.registrant.city %>,
 			      <%= State.where(:id=>order_item.registrant.state_id).first.abbreviation %>
 			      <%= order_item.registrant.zip %><br>
 			      <%= order_item.registrant.email %><br>
 			      <%= order_item.registrant.phone%> (p)<br>
 			      <%= order_item.registrant.cell %> (c)<br>
 			    </td>

 			    <td style="padding:20px 3px">
 			      <strong><%= order_item.course.title %></strong><br><br>
 			      <%= order_item.course_date.start_date.strftime("%m/%d/%Y") %>-
 			      <%= order_item.course_date.end_date.strftime("%m/%d/%Y") %><br>
 			      <%= order_item.course_date.sku %><br>
 			    </td>

 			    <td style="padding:20px 3px">
 			      <% if order_item.is_www %>
 			        <strong>
 			          Credit Card: <%= OrderTransaction.where(:order_id=>order_item.order_id).first.message if OrderTransaction.where(:order_id=>order_item.order_id).present? %><br>
 			          <%= order_item.created_at.strftime("%m/%d/%Y %H:%M:%S") %>
 			        </strong>
 			      <% end %>
 			      <% if order_item.is_purchaseorder %>
 			        <strong>
 			          PO# <%= order_item.po_number %><br>
     			      <%= order_item.created_at.strftime("%m/%d/%Y %H:%M:%S") %>
 			        </strong>
 			      <% end %>
 			      <br><br>
 			      <strong>Purchaser:</strong><br>
 			      <%= order_item.order.first_name %>
 			      <%= order_item.order.last_name %><br>
 			      <%= order_item.order.address %><br>
 			      <%= order_item.order.city %>,
 			      <%= State.where(:id=>order_item.order.state_id).first.abbreviation %>
 			      <%= order_item.order.zip %><br>
 			      <%= order_item.order.email %><br>
 			      <%= order_item.order.phone%> (p)<br>

 			    </td>
 			    
 			    <td style="padding:20px 3px" class="confirmation_<%=order_item.id%>">
 			      <%=render :partial=>"confirmation", :locals=>{:order_item=>order_item} %>
 			    </td>


			</tr>
			<%end%>
			

		</table>
		<!--<a href="#" class="next_10">View Next 10</a>-->
		<br>
		<%=paginate @order_items, :search_term=>params[:search_term], :from=>params[:from], :to=>params[:to]unless request.path.include? 'search'%>
		
		</div>
		<div class="footer"></div>
		</div>
		

app/views/admin/order_items/new.html.erb
<h1>New order_item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/admin/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @order_item.order_id %>
</p>

<p>
  <b>Course:</b>
  <%= @order_item.course_id %>
</p>

<p>
  <b>Course date:</b>
  <%= @order_item.course_date_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @order_item.quantity %>
</p>

<p>
  <b>Transaction:</b>
  <%= @order_item.transaction_id %>
</p>


<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>