config/routes.rb
Naeti::Application.routes.draw do

  resources :waitinglists

  resources :coursedates

  resources :credit_card_types

  resources :expiration_years

  resources :expiration_months

  resources :states

  devise_for :users
  
  
  resources :content_blocks

  resources :order_items

  resources :shopping_cart_items

  resources :user_roles

  resources :orders

  resources :shopping_carts

  resources :course_registrants

  resources :course_assets

  resources :course_categories

  resources :course_dates

  resources :on_site_trainings

  resources :checkouts
  

  match '/admin', :to=>"admin#index"
  match '/reports', :to=>"admin#reports"
  
  match '/instructors', :to=>"instructors#index"
  match '/instructors/course/:course_id', :to=>"courses#admin_instructor_edit"
  match '/admin/course/:course_id', :to=>"courses#admin_instructor_edit"
  
  match '/instructors/courses', :to=>"courses#instructor_list"
  match '/instructors/search_courses', :to=>"instructors#instructor_search"
  
  match '/on-site-training', :to=>"site#on_site_training"

  resources :courses do
    collection do
      post :search
    end
  end
  
 match '/courses/register/:friendly_course_url', :to=>"courses#register"
  
 match '/courses/:course_id/export_emails', :to=>"courses#export_emails"
 match '/courses/:course_id/export_xls', :to=>"courses#export_xls"
 match '/courses/:course_id/export_pdf', :to=>"courses#export_pdf", :defaults => { :format => 'pdf' }
 match '/courses/:course_id/coursereport-:course_id-:datestamp', :to=>"courses#export_pdf", :defaults=>{:format=>"pdf"}
  

  match '/users/:user_id/add_to_course', :to=>"users#add_to_course"
  
  resources :users do
    collection do
      post :search
      post :upload
      post :user_admin
    end
  end

  match '/:friendly_url', :to=>"site#static_page"
  

  namespace :admin do
    resources :registrants
    resources :assets
    resources :user_assets
    resources :course_assets
    resources :order_items do
      collection do
        post :search
        get :confirm
      end
    end  
    resources :courses do
      collection do
        post :search
        post :upload
        post :send_reminder
      end
    end  
  end
  
  

  root :to => "site#index"

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :shopping_cart
  has_many :transactions, :class_name => "OrderTransaction"
  has_many  :order_items
  belongs_to  :user
  
  default_scope order("created_at desc")
  
  attr_accessor :card_number, :card_verification, :is_purchase_order, :po_number

  validate_on_create :validate_card
  
  def purchase_order
    shopping_cart.update_attribute(:purchased_at, Time.now)
    create_purchase_order_items
    true
  end
  
  def purchase
  
    response = GATEWAY.purchase(price_in_cents, credit_card, purchase_options)
    transactions.create!(:action => "purchase", :amount => price_in_cents, :response => response)
    
    if (Rails.env=="production")
      shopping_cart.update_attribute(:purchased_at, Time.now) if response.success?
      create_order_items if response.success?
      response.success?
    else
      shopping_cart.update_attribute(:purchased_at, Time.now)
      create_order_items
      true
    end        
  end
  
  def price_in_cents
    (shopping_cart.total*100).round
  end

  private

  def create_purchase_order_items  
    ShoppingCartItem.where(:shopping_cart_id=>shopping_cart.id).each do |cart| 
      @order_item = OrderItem.new
      @order_item.course_id = cart.course_id
      @order_item.course_date = cart.course_date
      @order_item.registrant_id= cart.registrant_id
      @order_item.order_id = self.id
      @order_item.is_confirmed= false
      @order_item.is_purchaseorder= true
      @order_item.po_number = self.po_number
      @order_item.save 
    end	
  end
    
  def create_order_items
    ShoppingCartItem.where(:shopping_cart_id=>shopping_cart.id).each do |cart| 
      @order_item = OrderItem.new
      @order_item.course_id = cart.course_id
      @order_item.course_date = cart.course_date
      @order_item.registrant_id= cart.registrant_id
      @order_item.order_id = self.id
      @order_item.is_confirmed= true
      @order_item.is_www= true
      @order_item.save 
    end	
  end
  
  def purchase_options
    {
      :ip => ip_address,
      :billing_address => {
        :name     => "#{first_name} #{last_name}" ,
        :address1 => address,
        :city     => city,
        :state_id    => State.where(:id=>10).first.abbreviation,
        :country  => "US",
        :zip      => zip
      },
      :order_id => rand(Time.now) #shopping_cart.id
    }
  end
  
  def validate_card
  
    if is_purchase_order.blank?
      unless credit_card.valid?
        credit_card.errors.full_messages.each do |message|
          errors.add_to_base message
        end
      end
    else
    
      errors.add(:first_name, "cannot be blank") if first_name.blank?
      errors.add(:last_name, "cannot be blank") if last_name.blank?
      errors.add(:address, "cannot be blank") if address.blank?
      errors.add(:city, "cannot be blank") if city.blank?
      errors.add(:state_id, "cannot be blank") if state_id.blank?
      errors.add(:zip, "cannot be blank") if zip.blank?
      errors.add(:email, "cannot be blank") if email.blank?
      errors.add(:phone, "cannot be blank") if phone.blank?
      errors.add(:po_number, "cannot be blank") if po_number.blank?
    end
  end
  
  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :type               => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => first_name,
      :last_name          => last_name
    )
  end
end

app/controllers/admin/orders_controller.rb
#NEEDS TO BE REFACTORED FOR ADMIN
class OrdersController < ApplicationController
  before_filter :authenticate_admin
  
  # GET /orders
  # GET /orders.xml
  def index
    @admin_section =  true
    @page_title = "Transactions"
    @orders = Order.paginate(:all, :per_page=>10, :page=>params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.xml
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.xml
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.xml
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to(@order, :notice => 'Order was successfully created.') }
        format.xml  { render :xml => @order, :status => :created, :location => @order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.xml
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to(@order, :notice => 'Order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.xml
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to(orders_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  #before_filter :authenticate
  
  def new
  
    @page_title = "Register for NAETI Courses"
    @padding = true
    retrieve_shopping_cart
     
    @order = Order.new
     
    current_user.present? ? @user = current_user : @user = User.new

    respond_to do |format|
      format.html {}
      format.xml  {}
      format.js {}    
    end
    
  end
  

  def create
    retrieve_shopping_cart
    @order = @shopping_cart.build_order(params[:order])
    @order.ip_address = request.remote_ip
    @order.user_id = current_user.id 
    
    respond_to do |format|
      if @order.save
        if @order.is_purchase_order.present?
          @order.purchase_order
          
          Postoffice.admin_receipt_for_purchase(@order, @total).deliver
          Postoffice.user_receipt_for_purchase(@order, @total).deliver

          @order.order_items.each do |item| 
            Postoffice.registrant_receipt_for_purchase(item).deliver
          end
            
          format.js {}
        else
          if @order.purchase
            Postoffice.admin_receipt_for_purchase(@order, @total).deliver
            Postoffice.user_receipt_for_purchase(@order, @total).deliver
            
            @order.order_items.each do |item| 
              Postoffice.registrant_receipt_for_purchase(item).deliver
            end
            
            format.js {}
            #render :action => "success"
          else
            @order.errors.add :base, "Invalid credit card"
            format.js {}
            #render :action => "failure"
          end
        end
      else
        format.js {}
      end
    end
    
  end
    
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_date_id %><br />
    <%= f.text_field :course_date_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/admin/orders/index.html.erb
<div id="inner">

<div style="padding:15px">
	

	<div id="large_table">
	<div id="header_bg">
	<table colspan="4" class="zebra"  >
		<tr class="header">
			<th>Course</th>
			<th >Name</th>
			<th >Address</th>
			<th width="100">Paid</th>
		</tr>
		<%for order in @orders%>
		<%offline = ""%>
		
		<tr>
			<td ><%for item in order.order_items%><%=item.course.title%><%if item.offline_transaction_notes%><%offline = offline + item.offline_transaction_notes%><%end%><br /><br /><%end%></td>
			<td class="small"><%=order.user.name%></td>
			<td class="small">
				<%=raw order.user.full_address%>
			</td>
			<td class="small"><%if offline == ""%>Online<%else%>Offline (Notes: <%=raw offline%>)<%end%>
		</tr>
		<%end%>
		
	</table>
	<%=will_paginate @orders%>
	</div>
	<div class="footer"></div>
	</div>
	
	
	
</div>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Course:</b>
  <%= @order.course_id %>
</p>

<p>
  <b>User:</b>
  <%= @order.user_id %>
</p>

<p>
  <b>Course date:</b>
  <%= @order.course_date_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @order.quantity %>
</p>

<p>
  <b>Transaction:</b>
  <%= @order.transaction_id %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>