config/routes.rb
Naeti::Application.routes.draw do

  resources :waitinglists

  resources :coursedates

  resources :credit_card_types

  resources :expiration_years

  resources :expiration_months

  resources :states

  devise_for :users
  
  
  resources :content_blocks

  resources :order_items

  resources :shopping_cart_items

  resources :user_roles

  resources :orders

  resources :shopping_carts

  resources :course_registrants

  resources :course_assets

  resources :course_categories

  resources :course_dates

  resources :on_site_trainings

  resources :checkouts
  

  match '/admin', :to=>"admin#index"
  match '/reports', :to=>"admin#reports"
  
  match '/instructors', :to=>"instructors#index"
  match '/instructors/course/:course_id', :to=>"courses#admin_instructor_edit"
  match '/admin/course/:course_id', :to=>"courses#admin_instructor_edit"
  
  match '/instructors/courses', :to=>"courses#instructor_list"
  match '/instructors/search_courses', :to=>"instructors#instructor_search"
  
  match '/on-site-training', :to=>"site#on_site_training"

  resources :courses do
    collection do
      post :search
    end
  end
  
 match '/courses/register/:friendly_course_url', :to=>"courses#register"
  
 match '/courses/:course_id/export_emails', :to=>"courses#export_emails"
 match '/courses/:course_id/export_xls', :to=>"courses#export_xls"
 match '/courses/:course_id/export_pdf', :to=>"courses#export_pdf", :defaults => { :format => 'pdf' }
 match '/courses/:course_id/coursereport-:course_id-:datestamp', :to=>"courses#export_pdf", :defaults=>{:format=>"pdf"}
  

  match '/users/:user_id/add_to_course', :to=>"users#add_to_course"
  
  resources :users do
    collection do
      post :search
      post :upload
      post :user_admin
    end
  end

  match '/:friendly_url', :to=>"site#static_page"
  

  namespace :admin do
    resources :registrants
    resources :assets
    resources :user_assets
    resources :course_assets
    resources :order_items do
      collection do
        post :search
        get :confirm
      end
    end  
    resources :courses do
      collection do
        post :search
        post :upload
        post :send_reminder
      end
    end  
  end
  
  

  root :to => "site#index"

end

app/models/course_asset.rb
class CourseAsset < ActiveRecord::Base
  
  default_scope order("updated_at desc")
  
  
  belongs_to  :course
  
  
  has_attached_file :asset 

  validates_presence_of :title, :description
  
  
  validates_attachment_size :asset, :less_than => 20.megabytes, :if => Proc.new { |asset| asset.asset_file_name != nil }
 

  
end

app/controllers/admin/course_assets_controller.rb
class Admin::CourseAssetsController < ApplicationController
  before_filter :authenticate_admin

  # GET /course_assets
  # GET /course_assets.xml
  def index
    @course_assets = CourseAsset.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @course_assets }
    end
  end

  # GET /course_assets/1
  # GET /course_assets/1.xml
  def show
    @course_asset = CourseAsset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course_asset }
    end
  end

  # GET /course_assets/new
  # GET /course_assets/new.xml
  def new
    @course_asset = CourseAsset.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course_asset }
    end
  end

  # GET /course_assets/1/edit
  def edit
    @course_asset = CourseAsset.find(params[:id])
  end

  # POST /course_assets
  # POST /course_assets.xml
  def create
    @admin_section = true

    @course_asset = CourseAsset.new(params[:course_asset])

    respond_to do |format|
      if @course_asset.save
        format.html { redirect_to(@course_asset, :notice => 'File(s) were successfully uploaded.') }
        format.xml  { render :xml => @course_asset, :status => :created, :location => @course_asset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course_asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /course_assets/1
  # PUT /course_assets/1.xml
  def update
    @course_asset = CourseAsset.find(params[:id])

    respond_to do |format|
      if @course_asset.update_attributes(params[:course_asset])
        format.html { redirect_to(@course_asset, :notice => 'Course asset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course_asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /course_assets/1
  # DELETE /course_assets/1.xml
  def destroy

    @course = CourseAsset.where(:id=>params[:id]).first.course_id
    @course_asset = CourseAsset.where(:id=>params[:id]).first
    @course_asset.destroy

    respond_to do |format|
      format.html { redirect_to(admin_course_url(@course.to_param)<<"#tabs-4") }
      format.js {}
      format.xml  { head :ok }
    end
  end

end

app/helpers/course_assets_helper.rb
module CourseAssetsHelper
end

app/views/admin/course_assets/_form.html.erb
<%= form_for(@course_asset) do |f| %>
  <% if @course_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_asset.errors.count, "error") %> prohibited this course_asset from being saved:</h2>

      <ul>
      <% @course_asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :asset_file_name %><br />
    <%= f.text_field :asset_file_name %>
  </div>
  <div class="field">
    <%= f.label :asset_content_type %><br />
    <%= f.text_field :asset_content_type %>
  </div>
  <div class="field">
    <%= f.label :asset_file_size %><br />
    <%= f.text_field :asset_file_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/course_assets/_show.html.erb
<div class="user-asset-box" style="margin-left:15px;margin-top:15px"> 
  <h2 style="width:95%">Current Files</h2>
  <%= "<p>There are no files</p>".html_safe if CourseAsset.where(:course_id=>@course.id).blank? %>
  <% CourseAsset.where(:course_id=>@course.id).each do |course_asset| %>
    <div id="course_asset_<%= course_asset.id %>" style="clear:both">
      <p>  
        <%= link_to course_asset.title, course_asset.asset.url %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to image_tag("delete_btn.png", :style=>"width:16px;height:16px;"), admin_course_asset_path(course_asset), :confirm => 'Are you sure you want to delete this item?', :method => :delete, :remote=>true %>     
      </p>
    </div>
  <% end %>

</div>

app/views/admin/course_assets/destroy.js.erb
$('#<%= "course_asset_" + @course_asset.id.to_s %>').remove();

app/views/admin/course_assets/edit.html.erb
<h1>Editing course_asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_asset %> |
<%= link_to 'Back', course_assets_path %>

app/views/admin/course_assets/index.html.erb
<h1>Listing course_assets</h1>

<table>
  <tr>
    <th>Course</th>
    <th>Title</th>
    <th>Description</th>
    <th>Asset file name</th>
    <th>Asset content type</th>
    <th>Asset file size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @course_assets.each do |course_asset| %>
  <tr>
    <td><%= course_asset.course_id %></td>
    <td><%= course_asset.title %></td>
    <td><%= course_asset.description %></td>
    <td><%= course_asset.asset_file_name %></td>
    <td><%= course_asset.asset_content_type %></td>
    <td><%= course_asset.asset_file_size %></td>
    <td><%= link_to 'Show', course_asset %></td>
    <td><%= link_to 'Edit', edit_course_asset_path(course_asset) %></td>
    <td><%= link_to 'Destroy', course_asset, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course asset', new_course_asset_path %>

app/views/admin/course_assets/new.html.erb
<h1>New course_asset</h1>

<%= render 'form' %>

<%= link_to 'Back', course_assets_path %>

app/views/admin/course_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Course:</b>
  <%= @course_asset.course_id %>
</p>

<p>
  <b>Title:</b>
  <%= @course_asset.title %>
</p>

<p>
  <b>Description:</b>
  <%= @course_asset.description %>
</p>

<p>
  <b>Asset file name:</b>
  <%= @course_asset.asset_file_name %>
</p>

<p>
  <b>Asset content type:</b>
  <%= @course_asset.asset_content_type %>
</p>

<p>
  <b>Asset file size:</b>
  <%= @course_asset.asset_file_size %>
</p>


<%= link_to 'Edit', edit_course_asset_path(@course_asset) %> |
<%= link_to 'Back', course_assets_path %>