config/routes.rb
Naeti::Application.routes.draw do

  resources :waitinglists

  resources :coursedates

  resources :credit_card_types

  resources :expiration_years

  resources :expiration_months

  resources :states

  devise_for :users
  
  
  resources :content_blocks

  resources :order_items

  resources :shopping_cart_items

  resources :user_roles

  resources :orders

  resources :shopping_carts

  resources :course_registrants

  resources :course_assets

  resources :course_categories

  resources :course_dates

  resources :on_site_trainings

  resources :checkouts
  

  match '/admin', :to=>"admin#index"
  match '/reports', :to=>"admin#reports"
  
  match '/instructors', :to=>"instructors#index"
  match '/instructors/course/:course_id', :to=>"courses#admin_instructor_edit"
  match '/admin/course/:course_id', :to=>"courses#admin_instructor_edit"
  
  match '/instructors/courses', :to=>"courses#instructor_list"
  match '/instructors/search_courses', :to=>"instructors#instructor_search"
  
  match '/on-site-training', :to=>"site#on_site_training"

  resources :courses do
    collection do
      post :search
    end
  end
  
 match '/courses/register/:friendly_course_url', :to=>"courses#register"
  
 match '/courses/:course_id/export_emails', :to=>"courses#export_emails"
 match '/courses/:course_id/export_xls', :to=>"courses#export_xls"
 match '/courses/:course_id/export_pdf', :to=>"courses#export_pdf", :defaults => { :format => 'pdf' }
 match '/courses/:course_id/coursereport-:course_id-:datestamp', :to=>"courses#export_pdf", :defaults=>{:format=>"pdf"}
  

  match '/users/:user_id/add_to_course', :to=>"users#add_to_course"
  
  resources :users do
    collection do
      post :search
      post :upload
      post :user_admin
    end
  end

  match '/:friendly_url', :to=>"site#static_page"
  

  namespace :admin do
    resources :registrants
    resources :assets
    resources :user_assets
    resources :course_assets
    resources :order_items do
      collection do
        post :search
        get :confirm
      end
    end  
    resources :courses do
      collection do
        post :search
        post :upload
        post :send_reminder
      end
    end  
  end
  
  

  root :to => "site#index"

end

app/views/shared/_admin_nav.html.erb
<ul id="section_nav">
		<li><%=link_to "Admin Home", admin_path %></li>
		<li><%=link_to "Courses Admin", admin_courses_path %></li>
		<li><a href="/course_categories">Course Category Admin</a></li>
		<li><a href="/users">User/Instructor Admin</a></li>
		<li><%=link_to "Images/Assets Admin", admin_assets_path %></li>
		<li><%=link_to "Transactions", admin_order_items_path %></li>
		<li><a href="/reports">Reports</a></li>
		<li><a href="/content_blocks">Edit Pages</a></li>
</ul>

app/views/shared/_instructor_nav.html.erb
<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		$(".zebra tr:nth-child(odd) td").css("background","#f4f5f4");
	})
</script>

<ul id="section_nav">
		<li><a href="/instructors">Instructor Dashboard</a></li>
		<li><a href="/instructors/courses">Events Admin</a></li>
</ul>

app/views/shared/_normal_nav.html.erb
<ul id="section_nav">
	<li><a href="/qualification-statement">Qualification Statement</a></li>
    <li><%=link_to "Register for Courses", courses_path %></li>
	<li><a href="/course-dates">Course Dates</a></li>
	<li><a href="/on-site-training">On-Site Training</a></li>
	<li><a href="https://secure2.360training.com/vu3/index.cfm?event=home&cid=2697">Online Training</a></li>
	<li><a href="/training-locations">Training Locations</a></li>
	<li><a href="/testimonials">Testimonials</a></li>
	<li><a href="/photo-gallery">Photo Gallery</a></li>
	<li><a href="/directions">Directions</a></li>
	<li><a href="/meet-the-staff">Meet the Staff</a></li>
	<li><%=link_to "View Courses", courses_path, :class=>"view_courses_btn" %></li>
	<li><%=link_to "Course Registration", courses_path, :class=>"course_registration" %></li>
	<li><a href="/contact" class="contact_btn">Contact Naeti</a></li>
</ul>